#!C:\Users\sudhi\Downloads\Sagar_Pathak\IIT_Bhilai\ML\XAI_assistant_ML\XAI_Assistant_ML\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
